### ISSUE TITLE
support path key prefix selection in Config

### ISSUE THREAD

**Issue by cwlbraa** [carvel-dev/kapp#62]
I'd like to write a rebase rule that always pulls all of the `cert-manager.io/` annotations for secrets out of the cluster, but right now I think I have to write that like this:

```
rebaseRules:
- path: [metadata, annotations, "cert-manager.io/alt-names"]
  type: copy
  sources: [new, existing]
  resourceMatchers: &opaqueSecrets
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret, type: Opaque}

- path: [metadata, annotations, "cert-manager.io/certificate-name"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets

- path: [metadata, annotations, "cert-manager.io/common-name"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets

- path: [metadata, annotations, "cert-manager.io/ip-sans"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets

- path: [metadata, annotations, "cert-manager.io/issuer-kind"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets

- path: [metadata, annotations, "cert-manager.io/issuer-name"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets

- path: [metadata, annotations, "cert-manager.io/uri-sans"]
  type: copy
  sources: [new, existing]
  resourceMatchers: *opaqueSecrets
```

when really what I want is something like:

```
rebaseRules:
- path: [metadata, annotations, {prefixed: "cert-manager.io/"}]
  type: copy
  sources: [new, existing]
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret, type: Opaque}
```

**Tasks**
- [x] rebase rules to support regex as new field in config path
- [ ] diff stage to support new field. changes in  (mod_field_copy, remove, overlay_contract mod - resources package) 
- [ ] test ownership rules, label scoping rule
- [ ] e2e test case
- [ ] documentation
